name: Deploy Dashboard Production

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
  workflow_dispatch:
env:
  IMAGE_NAME: care-dashboard

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    name: Test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('package-lock.json', 'package.json', 'Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Test build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Run tests
        run: |
          echo "running tests..."

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-production-manipur:
    #    needs: test
    name: Build & Push Production Manipur
    if: github.ref == 'refs/heads/production' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update env
        run: |
          echo "VITE_API_URL=$VITE_API_URL" > .env
          echo "VITE_NAV_LOGO=$VITE_NAV_LOGO" >> .env
          cp -f districts/manipur.json districts.json
        env:
          VITE_API_URL: "https://careapi.mn.gov.in"
          VITE_NAV_LOGO: "https://cdn.coronasafe.network/light-logo.svg"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=production-manipur,enable=${{ github.ref == 'refs/heads/production' }}
            type=raw,value=production-manipur-${{ github.run_number }}-{{date 'YYYYMMDD'}}-{{sha}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('package-lock.lock', 'package.json', 'Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-production-karnataka:
    #    needs: test
    name: Build & Push Production Karnataka
    if: github.ref == 'refs/heads/production' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update env
        run: |
          echo "VITE_API_URL=$VITE_API_URL" > .env
          echo "VITE_NAV_LOGO=$VITE_NAV_LOGO" >> .env
          cp -f districts/karnataka.json districts.json
        env:
          VITE_API_URL: "https://careapi.karnataka.care"
          VITE_NAV_LOGO: "https://cdn.coronasafe.network/light-logo.svg"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=production-karnataka,enable=${{ github.ref == 'refs/heads/production' }}
            type=raw,value=production-karnataka-${{ github.run_number }}-{{date 'YYYYMMDD'}}-{{sha}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('package-lock.lock', 'package.json', 'Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-production-nagaland:
    #    needs: test
    name: Build & Push Production Nagaland
    if: github.ref == 'refs/heads/production' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update env
        run: |
          echo "VITE_API_URL=$VITE_API_URL" > .env
          echo "VITE_NAV_LOGO=$VITE_NAV_LOGO" >> .env
          cp -f districts/nagaland.json districts.json
        env:
          VITE_API_URL: "https://nl-careapi.10bedicu.in"
          VITE_NAV_LOGO: "https://cdn.coronasafe.network/light-logo.svg"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=production-nagaland,enable=${{ github.ref == 'refs/heads/production' }}
            type=raw,value=production-nagaland-${{ github.run_number }}-{{date 'YYYYMMDD'}}-{{sha}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('package-lock.lock', 'package.json', 'Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy-production-manipur:
    needs: build-production-manipur
    name: Deploy to GKE Manipur
    runs-on: ubuntu-latest
    environment:
      name: Production-Manipur
      url: https://10bedicu.mn.gov.in
    steps:
      - name: Checkout Kube Config
        uses: actions/checkout@v3
        with:
          repository: coronasafe/mn-care-infra
          token: ${{ secrets.GIT_ACCESS_TOKEN  }}
          path: kube
          ref: main

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Get the GKE credentials, so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: install kubectl
        uses: azure/setup-kubectl@v3.0
        with:
          version: "v1.23.6"
        id: install

      - name: Deploy Care Dashboard Production
        run: |
          mkdir -p $HOME/.kube/
          cd kube/deployments/
          sed -i -e "s/_BUILD_NUMBER_/${GITHUB_RUN_NUMBER}/g" care-dashboard.yaml
          sed -i -e "s/production-latest/production-manipur/g" care-dashboard.yaml
          kubectl apply -f care-dashboard.yaml

  deploy-production-karnataka:
    needs: build-production-karnataka
    name: Deploy to GKE Karnataka
    runs-on: ubuntu-latest
    environment:
      name: Production-Karnataka
      url: https://10bedicu.karnataka.care
    steps:
      - name: Checkout Kube Config
        uses: actions/checkout@v3
        with:
          repository: coronasafe/ka-care-infra
          token: ${{ secrets.GIT_ACCESS_TOKEN  }}
          path: kube
          ref: main

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}

  deploy-production-nagaland:
    needs: build-production-nagaland
    name: Deploy to GKE Nagaland
    runs-on: ubuntu-latest
    environment:
      name: Production-Nagaland
      url: https://10bedicu.nagaland.gov.in
    steps:
      - name: Checkout Kube Config
        uses: actions/checkout@v3
        with:
          repository: coronasafe/nl-care-infra
          token: ${{ secrets.GIT_ACCESS_TOKEN  }}
          path: kube
          ref: main

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Get the GKE credentials, so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: install kubectl
        uses: azure/setup-kubectl@v3.0
        with:
          version: "v1.23.6"
        id: install

      - name: Deploy Care Dashboard Production
        run: |
          mkdir -p $HOME/.kube/
          cd kube/deployments/
          sed -i -e "s/_BUILD_NUMBER_/${GITHUB_RUN_NUMBER}/g" care-dashboard.yaml
          sed -i -e "s/production-latest/production-karnataka/g" care-dashboard.yaml
          kubectl apply -f care-dashboard.yaml
